title: Hossain Quantum Research
description: Computational Materials, AI, and Quantum Algorithms

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:name/

  projects:
    output: true
    permalink: /projects/:name/

  publications:
    output: true
    permalink: /publications/:name/
